// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrCA3Kxx4_0nmTsIbZeM-6qUVaQYKg8tU',
    appId: '1:520753114225:web:53c10f9e75403b02b4ffd0',
    messagingSenderId: '520753114225',
    projectId: 'todo-d1233',
    authDomain: 'todo-d1233.firebaseapp.com',
    storageBucket: 'todo-d1233.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABfJHyWM05i6SCBruOgW9pSkU4JUpPdnc',
    appId: '1:520753114225:android:41e00c66bdf0f145b4ffd0',
    messagingSenderId: '520753114225',
    projectId: 'todo-d1233',
    storageBucket: 'todo-d1233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiub8o_wXemTAWFCvIhTeqB9uO0_pSNEI',
    appId: '1:520753114225:ios:73318b8321c1b9aeb4ffd0',
    messagingSenderId: '520753114225',
    projectId: 'todo-d1233',
    storageBucket: 'todo-d1233.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiub8o_wXemTAWFCvIhTeqB9uO0_pSNEI',
    appId: '1:520753114225:ios:73318b8321c1b9aeb4ffd0',
    messagingSenderId: '520753114225',
    projectId: 'todo-d1233',
    storageBucket: 'todo-d1233.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrCA3Kxx4_0nmTsIbZeM-6qUVaQYKg8tU',
    appId: '1:520753114225:web:f353c5488a4a89fcb4ffd0',
    messagingSenderId: '520753114225',
    projectId: 'todo-d1233',
    authDomain: 'todo-d1233.firebaseapp.com',
    storageBucket: 'todo-d1233.firebasestorage.app',
  );
}
